#!/usr/bin/env bash

set -euo pipefail

if [ "$(id -u)" -ne 0 ]; then
    echo "[ERROR] script must be run as root"
    exit 1
fi

RUGIX_SYSTEM_INFO=$(rugix-ctrl system info)

ACTIVE_GROUP=$(echo "$RUGIX_SYSTEM_INFO" | jq -r '.boot.activeGroup')
DEFAULT_GROUP=$(echo "$RUGIX_SYSTEM_INFO" | jq -r '.boot.defaultGroup')

if [ "$ACTIVE_GROUP" != "$DEFAULT_GROUP" ]; then
    # Delay a bit to allow the system to settle.
    sleep 30
    nexigon-agent events emit --category "org.rugix.ota" \
        --attribute "activeGroup=$(jq -n --arg group "$ACTIVE_GROUP" '$group')" \
        --attribute "defaultGroup=$(jq -n --arg group "$DEFAULT_GROUP" '$group')" \
        '"committing system update"' || true
    rugix-ctrl system commit
    RUGIX_SYSTEM_INFO=$(rugix-ctrl system info)

    ACTIVE_GROUP=$(echo "$RUGIX_SYSTEM_INFO" | jq -r '.boot.activeGroup')
    DEFAULT_GROUP=$(echo "$RUGIX_SYSTEM_INFO" | jq -r '.boot.defaultGroup')
    nexigon-agent events emit --category "org.rugix.ota" \
        --attribute "activeGroup=$(jq -n --arg group "$ACTIVE_GROUP" '$group')" \
        --attribute "defaultGroup=$(jq -n --arg group "$DEFAULT_GROUP" '$group')" \
        '"update committed"' || true
fi
