# spellchecker:ignore taiki dtolnay Taplo xvzf musleabihf gnueabihf msvc clippy bindgen

name: CI Pipeline

on:
  push:
    branches:
      - main
      - ci
  pull_request:
  workflow_dispatch:

env:
  NEXIGON_REPOSITORY: ${{ vars.NEXIGON_REPOSITORY }}
  NEXIGON_PACKAGE: ${{ vars.NEXIGON_PACKAGE }}

jobs:
  prepare-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prepare PR Build
        if: github.event_name == 'pull_request'
        run: echo "VERSION=ci-$GITHUB_SHA" >.release-env
      - name: Create Release
        if: github.event_name != 'pull_request'
        run: |
          cat <<EOF >.nexigon-cli.toml
            hub-url = "${{ secrets.NEXIGON_HUB_URL }}"
            token = "${{ secrets.NEXIGON_USER_TOKEN }}"
          EOF
          curl -sfSL https://install.nexigon.dev/download-cli.sh | sh
          export NEXIGON_CLI="./nexigon-cli"
          touch .env
          ./scripts/prepare-release.sh
      - name: Upload .release-env
        uses: actions/upload-artifact@v4
        with:
          name: release-env
          path: .release-env
          include-hidden-files: true

  build:
    name: Build (${{ matrix.system }})
    runs-on: ${{ matrix.os }}
    needs: prepare-release
    strategy:
      fail-fast: false
      matrix:
        include:
          - system: customized-efi-amd64
            os: ubuntu-24.04
          - system: customized-efi-arm64
            os: ubuntu-24.04-arm
          - system: customized-pi5
            os: ubuntu-24.04-arm
          - system: customized-pi4
            os: ubuntu-24.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download .release-env
        uses: actions/download-artifact@v4
        with:
          name: release-env
      - name: Configure PR Build
        if: github.event_name == 'pull_request'
        run: |
          cat <<'EOF' >.env
            NEXIGON_HUB_URL="https://ci.invalid"
            NEXIGON_TOKEN="ci-build-placeholder"
            NEXIGON_REPOSITORY="ci-build"
            NEXIGON_PACKAGE="ci-build"
          EOF
      - name: Configure Release Build
        if: github.event_name != 'pull_request'
        run: |
          cat <<EOF >.env
            NEXIGON_HUB_URL="${{ secrets.NEXIGON_HUB_URL }}"
            NEXIGON_TOKEN="${{ secrets.NEXIGON_DEPLOYMENT_TOKEN }}"
            NEXIGON_REPOSITORY="${{ env.NEXIGON_REPOSITORY }}"
            NEXIGON_PACKAGE="${{ env.NEXIGON_PACKAGE }}"
          EOF
      - name: Build
        run: ./scripts/build-release.sh "${{ matrix.system }}"
      - name: Upload
        if: github.event_name != 'pull_request'
        run: |
          cat <<EOF >.nexigon-cli.toml
            hub-url = "${{ secrets.NEXIGON_HUB_URL }}"
            token = "${{ secrets.NEXIGON_USER_TOKEN }}"
          EOF
          curl -sfSL https://install.nexigon.dev/download-cli.sh | sh
          export NEXIGON_CLI="./nexigon-cli"
          sudo chown -R "$(id -u):$(id -g)" build
          ./scripts/upload-release.sh
